In [2]:
import numpy as np

print("Numpy Version ", np.__version__)
arr = np.array([8, 4, 6, 0, 2])
print(arr)

Numpy Version  2.0.2
[8 4 6 0 2]


Type method (return type of data)

In [3]:
print("Type of Array ",type(arr))
print("Dimension of array is",arr.ndim)
d0= np.array(23)
print("Dimension of array is",d0.ndim)
fruit_list = np.array(['apple', 'banana', 'cherry'])
print(fruit_list)
print("Type of fruit list is",type(fruit_list))
fruit_list = np.array(fruit_list)
print("Type of fruit list is",type(fruit_list))

Type of Array  <class 'numpy.ndarray'>
Dimension of array is 1
Dimension of array is 0
['apple' 'banana' 'cherry']
Type of fruit list is <class 'numpy.ndarray'>
Type of fruit list is <class 'numpy.ndarray'>


Array Dimnension

In [10]:
import numpy as np

# 1_D Array
A= np.array([8,4,6,0,3])
print("1-D Array")
print(A)
print("\n")

# 2_D Array

B= np.array([[8,4,6,0,3], [4,9,7,8,6]])
print("2-D Array")
print(B)
print("\n")

# 3_D Array

C= np.array([[[8,4,6,0,3], [4,9,7,8,6], [6,0,8,0,3]]])
print("3-D Array")
print(C)
print("\n")

C_dimensions = C.ndim
print("Dimension of C is ", C_dimensions)


1-D Array
[8 4 6 0 3]


2-D Array
[[8 4 6 0 3]
 [4 9 7 8 6]]


3-D Array
[[[8 4 6 0 3]
  [4 9 7 8 6]
  [6 0 8 0 3]]]


Dimension of C is  3


Dimension Through ndim, Acessing array(2D,3D) elements

In [12]:
d1 = np.array([8,7,4,3])
print("The Dimension of array d1 is",d1.ndim)
print("Elemnts of array d1",d1)
d2= np.array([[58,78,98,54],[8,7,9,4],[5,7,9,5]])
print("Elemnts of array d2",d2)
print("The Dimension of array d2 is",d2.ndim)
print("Elements at (1,0) row 1 column 0 is ",d2[1,0])



The Dimension of array d1 is 1
Elemnts of array d1 [8 7 4 3]
Elemnts of array d2 [[58 78 98 54]
 [ 8  7  9  4]
 [ 5  7  9  5]]
The Dimension of array d2 is 2
Elements at (1,0) row 1 column 0 is  8


In [14]:
import numpy as np

d3array = np.array([
    [  # Depth 0
        [1, 2, 3],      # Row 0
        [4, 5, 6]       # Row 1
    ],
    [  # Depth 1
        [7, 8, 9],      # Row 0
        [10, 11, 12]    # Row 1
    ],
    [  # Depth 2
        [13, 14, 15],   # Row 0
        [16, 17, 18]    # Row 1
    ]
])

print("The dimension of array d3array is:", d3array.ndim)
print(d3array)

# d3array[depth][row][column]
item = d3array[2][0][0]   # Depth 2, Row 0, Column 0
print("Item at d3array[2][0][0] is:", item)


The dimension of array d3array is: 3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
Item at d3array[2][0][0] is: 13


Array Slicing

In [15]:
import numpy as np

# Numpy array slicing
d1 = np.array([6,8,1,2,54,5,3]) # 1-D Array
print("Elements of array d1 are ", d1)

# 1-D Array slicing "The result includes the start index, excludes the end index"
print("Elements slicing 'd1[1:5]' ", d1[1:5])

# Slice elements from start index[0] to index[3], index [3] excluded
print("Elements slicing 'd1[:3]' ", d1[:3])

# Slice elements from index[3] to last index
print("Elements slicing 'd1[3:]' ", d1[3:])

# Slice elements (negative slicing) from index[-3] to index[-1], index[-1] excluded
print("Elements slicing 'd1[-3:-1]' ", d1[-3:-1])

d2 = np.array([[5,9,3,4],[21,65,8,99],[56,98,1,2]]) # 2-D Array
print("Elements of array d2 are ", d2)

# 2-D Array slicing : Slice elements from array[0], index[1] to index[3], index [3] excluded
print("Elements slicing 'd2[0,1:3]' ", d2[0,1:3])

Elements of array d1 are  [ 6  8  1  2 54  5  3]
Elements slicing 'd1[1:5]'  [ 8  1  2 54]
Elements slicing 'd1[:3]'  [6 8 1]
Elements slicing 'd1[3:]'  [ 2 54  5  3]
Elements slicing 'd1[-3:-1]'  [54  5]
Elements of array d2 are  [[ 5  9  3  4]
 [21 65  8 99]
 [56 98  1  2]]
Elements slicing 'd2[0,1:3]'  [9 3]


Array slicing with step

In [16]:
import numpy as np

# Re-defining d1 from the previous step so this code works
d1 = np.array([6,8,1,2,54,5,3])

# Array slicing with step [index:index:step]
# print("Elements of array d1 are ",d1)
print("Array d1 slicing with step:d1[1:6:2] ",d1[1:6:2])

Array d1 slicing with step:d1[1:6:2]  [8 2 5]


NumPy Array Shape

In [17]:
import numpy as np

d1 = np.array([6,8,1,2,54,5,3])

# Array slicing with step [index:index:step]
# print("Elements of array d1 are ",d1)
print("Array d1 slicing with step:d1[1:6:2] ",d1[1:6:2])

Array d1 slicing with step:d1[1:6:2]  [8 2 5]


Flattren array

In [18]:
import numpy as np

# Flatten array
a2D = np.array([[1, 2], [3, 4]])
print("Array a2D", a2D)
flattened = a2D.reshape(-1) # array flatten through reshape
print(flattened)


Array a2D [[1 2]
 [3 4]]
[1 2 3 4]


Numpy Array Copy vs View

In [19]:
import numpy as np

# # b as a view of a
a = np.array([1, 2, 3, 4, 5, 6])
print("Array a",a)
b = a[:2]
print("Array b",b)
b += 1
print("Array b after increment of a",b)
print('Array a = ', a, ' ; array b = ', b)

#create a new array, using numpy.copy array
a = np.array([1, 2, 3, 4])
b = a[:2].copy()
b += 1
print('a = ', a, 'b = ', b)

Array a [1 2 3 4 5 6]
Array b [1 2]
Array b after increment of a [2 3]
Array a =  [2 3 3 4 5 6]  ; array b =  [2 3]
a =  [1 2 3 4] b =  [2 3]


Iterating 1-D Array

In [20]:
import numpy as np

d1 = np.array([6,8,1,2,54,5,3])
for x in d1:
    print(x)

6
8
1
2
54
5
3


Iterating 2-D Array

In [21]:
import numpy as np

d2 = np.array([[58,69,34,45],[25,65,68,99],[56,98,1,2]]) # 2-D Array
print("Elements of array d2 are ",d2)

for x in d2:
    for i in x:
        print(i)

Elements of array d2 are  [[58 69 34 45]
 [25 65 68 99]
 [56 98  1  2]]
58
69
34
45
25
65
68
99
56
98
1
2


Iterating 3D array

In [22]:
import numpy as np

# Defining a 3-D array
d3 = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]]
])

print("The dimension of array d3 is ", d3.ndim)
print(d3)

for x in d3:       # Loop through the 2D blocks
    for y in x:    # Loop through the rows in that block
        for z in y: # Loop through the items in that row
            print(z)

The dimension of array d3 is  3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18


iterating arrays using nditer

In [23]:
import numpy as np

d2 = np.array([[58,69,34,45],[25,65,68,99],[56,98,1,2]]) # 2-D Array
print("Elements of array d2 are ", d2)

# Using nditer avoids nested for-loops
for x in np.nditer(d2):
    print(x)

Elements of array d2 are  [[58 69 34 45]
 [25 65 68 99]
 [56 98  1  2]]
58
69
34
45
25
65
68
99
56
98
1
2


NUmpy joining arrays

In [24]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6])
print("Array 1: ", arr1)

arr2 = np.array([7, 8, 9, 10, 11, 12])
print("Array 2: ", arr2)

arr3 = np.concatenate((arr1, arr2))
print("Concatenated array: arr3", arr3)

Array 1:  [1 2 3 4 5 6]
Array 2:  [ 7  8  9 10 11 12]
Concatenated array: arr3 [ 1  2  3  4  5  6  7  8  9 10 11 12]


Joining array using Stack method

In [25]:
import numpy as np

arr1 = np.array([1, 2, 3])
print("Array 1: ", arr1)

arr2 = np.array([7, 8, 9])
print("Array 2: ", arr2)

# Stacking along axis=1 pairs the elements (column-wise)
arr3 = np.stack((arr1, arr2), axis=1)
print("Concatenated array through stack: arr3", arr3)

Array 1:  [1 2 3]
Array 2:  [7 8 9]
Concatenated array through stack: arr3 [[1 7]
 [2 8]
 [3 9]]


Spliting arrays

In [26]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6])
splitarr = np.array_split(arr1, 3)

print("Array 1 split into 3 arrays", splitarr)
print("Array 1", splitarr[0])
print("Array 2", splitarr[1])
print("Array 3", splitarr[2])


Array 1 split into 3 arrays [array([1, 2]), array([3, 4]), array([5, 6])]
Array 1 [1 2]
Array 2 [3 4]
Array 3 [5 6]


Numpy arrays searching

In [27]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6])

# Find the index where the value is 4
x = np.where(arr1 == 4)

print("Search index of 4", x)

Search index of 4 (array([3]),)


Search sorted array

In [28]:
import numpy as np

arr2 = np.array([3, 4, 5, 6, 7, 8])

# Find the index where the value 6 should be to maintain order
x = np.searchsorted(arr2, 6)

print("Index of 6 is", x)

Index of 6 is 3


Filtering Array

In [29]:
import numpy as np

arr = np.array([[58,69,34,45],[25,65,68,99],[56,98,1,2]])

# Create a filter (mask)
mask = arr > 45

# Apply the filter
new_array = arr[mask]

print(new_array)

[58 69 65 68 99 56 98]


Lab task

In [30]:
import numpy as np

# 1. Create a 3x3 matrix with values ranging from 2 to 10
# we use arange(2, 11) because the stop value is exclusive
matrix = np.arange(2, 11).reshape(3, 3)

# 2. Convert the array to a float type
matrix_float = matrix.astype(float)

# 3. Flatten the array and find max/min values
# Note: np.max and np.min work on the flattened version by default
flattened_view = matrix_float.flatten()
max_val = np.max(flattened_view)
min_val = np.min(flattened_view)

# Output Results
print("Original 3x3 Matrix (Float):")
print(matrix_float)
print("-" * 30)
print(f"Flattened Array: {flattened_view}")
print(f"Maximum Value:   {max_val}")
print(f"Minimum Value:   {min_val}")


Original 3x3 Matrix (Float):
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
------------------------------
Flattened Array: [ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
Maximum Value:   10.0
Minimum Value:   2.0
